first release on development branch.
vkupriya/go-gophermart pull request #1
Opened 2024-07-10 21:22 UTC by vkupriya

2024-07-24 16:12 UTC, s-shpak requested changes
1. Как и обсуждали на 1-1 необходимо покрыть код тестами
2. Необходимо добавить сжатие ответов/разжатие запросов

2024-07-24 16:12 UTC, s-shpak commented on go.mod
> +go 1.21.12
Почему не `1.22` ?

2024-07-24 16:12 UTC, s-shpak commented on cmd/gophermart/main.go
> +	log.Println("gophermart server stopped.")
Это сообщение желательно выводить используя свой кастомный логгер

2024-07-24 16:12 UTC, s-shpak commented on internal/gophermart/gophermart.go
> +	context.AfterFunc(ctx, func() {
Здесь потерялось возвращаемое значение: проигнорируй его явно, если не собираешься использовать

2024-07-24 16:12 UTC, s-shpak commented on internal/gophermart/config/config.go
> +	d := flag.String("d", "postgres://postgres:postgres@localhost:5432/gophermart?sslmode=disable", "PostgreSQL DSN")
Такие значения не надо хардкодить: в них есть пусть и дефолтные, но пароли. Просто завершай процесс с ошибкой, если это значение не было передано при старте

2024-07-24 16:12 UTC, s-shpak commented on internal/gophermart/config/config.go
> +	j := flag.String("j", "secret-key", "JWT key")
Аналогично

2024-07-24 16:12 UTC, s-shpak commented on internal/gophermart/config/config.go
> +	if envAddr, ok := os.LookupEnv("RUN_ADDRESS"); ok {
Мы говорили об этом на вебинаре: в финальном проекте, если это позволяют автотесты, то приоритет такой - дефолтные значения < переменные окружения < флаги

2024-07-24 16:12 UTC, s-shpak commented on internal/gophermart/gophermart.go
> +		logger.Sugar().Fatal(err)
Фаталиться в глубине кода нельзя

2024-07-24 16:12 UTC, s-shpak commented on internal/gophermart/gophermart.go
> +			errRec := recover()
Если паника возникла в хендлере, то этот `recover` ее не поймает: код хендлера исполняется в отдельной горутине. Необходимо использовать специальную `middleware` (или написать свою), для обработки таких событий

2024-07-24 16:12 UTC, s-shpak commented on internal/gophermart/gophermart.go
> +				err = fmt.Errorf("a panic occurred: %v", errRec)
```suggestion
				err = fmt.Errorf("a panic occurred: %w", errRec)
```

2024-07-24 16:12 UTC, s-shpak commented on internal/gophermart/gophermart.go
> +	if err := g.Wait(); err != nil {
А где происходит закрытие соединения с БД ?

2024-07-24 16:12 UTC, s-shpak commented on internal/gophermart/storage/storage.go
> +	createSchema := []string{
Необходимо использовать миграции

2024-07-24 16:12 UTC, s-shpak commented on internal/gophermart/storage/storage.go
> +	tx, err := pool.Begin(ctx)
Необходимо вызывать `Rollback`, если произошла ошибка. Посмотри как это обычно делается в случае работы с `pgx`

2024-07-24 16:12 UTC, s-shpak commented on internal/gophermart/server/handlers/handlers.go
> +	SvcUserAdd(user models.User) error
Кажется, что префикс `Svc` не нужен - метод и так уже принадлежит интерфейсу "Service"

2024-07-24 16:12 UTC, s-shpak commented on internal/gophermart/server/handlers/handlers.go
> +func NewGophermartHandler(service Service, cfg *models.Config) *GophermartHandler {
Тебе действительно нужно передавать весь объект `cfg` в этот конструктор ?

2024-07-24 16:12 UTC, s-shpak commented on internal/gophermart/server/handlers/handlers.go
> +	ErrorNoContextUser        string = "failed to get user from context value"
Зачем делать эти переменные экспортируемыми ?

2024-07-24 16:12 UTC, s-shpak commented on internal/gophermart/server/handlers/handlers.go
> +	ml := mw.NewMiddlewareLogger(gr.config)
Кажется, что логгер должен быть доступен другим `middleware`

2024-07-24 16:12 UTC, s-shpak commented on internal/gophermart/server/handlers/handlers.go
> +		fmt.Println(err)
deadcode

2024-07-24 16:12 UTC, s-shpak commented on internal/gophermart/server/handlers/handlers.go
> +	logger := gr.config.Logger
Эта часть кода повторятся во всех хендлерах, где требуется авторизация пользователя, может ее вынести в отдельную функцию ?

2024-07-24 16:12 UTC, s-shpak commented on internal/gophermart/server/middleware/auth.go
> +		// logger := m.config.Logger
deadcode

2024-07-24 16:12 UTC, s-shpak commented on internal/gophermart/service/service.go
> +func NewStore(c *models.Config) (Storage, error) {
Почему конструктор `Store` лежит в этом пакете ? Кажется, что было бы логичнее внедрять его как зависимость в `GophermartService` (передавать аргументом при инициализации этого объекта)

2024-07-24 16:12 UTC, s-shpak commented on internal/gophermart/service/service.go
> +	logger.Sugar().Debugf("user %s has been registered", user.UserID)
Используй лучше структурированное логирование, чем `Debugf`, например:

```suggestion
	logger.Sugar().Debugf(
	"user has been registered",
	"user ID", user.UserID,
)
```

2024-07-24 16:12 UTC, s-shpak commented on internal/gophermart/service/service.go
> +		tickerPeriod int64 = 10
1. Это значение лучше сделать конфигурируемым
2. Лучше, чтобы оно сразу передавалось в виде `time.Duration` в эту функцию

2024-07-24 16:12 UTC, s-shpak commented on internal/gophermart/service/service.go
> +					order.Status = "NEW"
Обсудили на 1-1

2024-07-24 16:12 UTC, s-shpak commented on internal/gophermart/service/service.go
> +				accrualOrder, err := g.SvcOrderGetAccrual(&order)
Необходимо отправлять параллельно несколько запросов к сервису accrual (можно использовать WorkerPool)

2024-07-24 16:12 UTC, s-shpak commented on internal/gophermart/service/service.go
> +func (g *GophermartService) SvcOrderGetAccrual(order *models.Order) (models.Order, error) {
Тебе надо правильно обрабатывать ситуацию, когда accrual присылает тебе статус-код `429 Too many requests`. Это обсужадется в тех. задании, и мы обсуждали на вебинаре. Если коротко, то как только был получен 429, воркеры должны не посылать новых запросов к сервису в течение интервала времени, указанного сервисом

2024-07-24 16:12 UTC, s-shpak commented on internal/gophermart/service/service.go
> +		httpTimeout       int   = 30
Эти значения должны быть конфигурируемыми

2024-07-24 16:12 UTC, s-shpak commented on internal/gophermart/service/service.go
> +	for retry <= retries {
Лучше использовать библиотеку для этого, типа https://github.com/hashicorp/go-retryablehttp или https://github.com/sethvargo/go-retry

2024-07-24 16:12 UTC, s-shpak commented on internal/gophermart/storage/storage.go
> +	var PgErr *pgconn.PgError
Почему с большой буквы ?

2024-07-24 16:12 UTC, s-shpak commented on internal/gophermart/storage/storage.go
> +	row = db.QueryRow(ctx, querySQL, userid)
Если ты делаешь несколько запросов к БД в рамках одной операции, то они должны делаться внутри транзакции

2024-07-25 12:30 UTC, vkupriya commented on go.mod
> +go 1.21.12
и правда, поменял на 1.22

2024-07-25 15:37 UTC, vkupriya commented on internal/gophermart/config/config.go
> +	if envAddr, ok := os.LookupEnv("RUN_ADDRESS"); ok {
Переделал. Не знал, как понять, что параметр используется по-умолчанию или был указан с командной строки - я просто сравниваю со значением по-умолчанию, и если совпадает, тогда ищу в переменных окружения.

2024-07-25 15:41 UTC, vkupriya commented on internal/gophermart/config/config.go
> +	d := flag.String("d", "postgres://postgres:postgres@localhost:5432/gophermart?sslmode=disable", "PostgreSQL DSN")
да, это я от лени - установил по-умолчанию, чтобы не указывать при локальном тестировании. Удалил и выдаю ошибку и останавливаюсь, если отсутствуют параметры такие как DSN и jwt secret.

2024-07-25 15:42 UTC, vkupriya commented on internal/gophermart/config/config.go
> +	j := flag.String("j", "secret-key", "JWT key")
Убрал значение по-умолчанию и выдаю ошибку при отсутствии.

2024-07-25 16:14 UTC, vkupriya commented on cmd/gophermart/main.go
> +	log.Println("gophermart server stopped.")
дублированное сообщение, уже выдаётся gophermart коде с использованием кастомного логгера.

2024-07-25 16:49 UTC, vkupriya commented on internal/gophermart/gophermart.go
> +		logger.Sugar().Fatal(err)
исправил.

2024-07-25 17:00 UTC, vkupriya commented on internal/gophermart/server/handlers/handlers.go
> +func NewGophermartHandler(service Service, cfg *models.Config) *GophermartHandler {
нет - я осознал ошибку, было просто удобно перебрасывать весь конфиг, но возникли трудности при тестировании. Теперь понял, что нужно пробрасывать только то, что нужно. Изменил код - вместо конфига передаю только логгер.

2024-07-25 17:02 UTC, vkupriya commented on internal/gophermart/server/handlers/handlers.go
> +	ml := mw.NewMiddlewareLogger(gr.config)
исправил.

2024-07-25 17:02 UTC, vkupriya commented on internal/gophermart/server/handlers/handlers.go
> +		fmt.Println(err)
похоронил.

2024-07-25 17:48 UTC, vkupriya commented on internal/gophermart/server/middleware/auth.go
> +		// logger := m.config.Logger
похоронил.

2024-07-25 17:52 UTC, vkupriya commented on internal/gophermart/server/handlers/handlers.go
> +	SvcUserAdd(user models.User) error
согласен - и так ясно, что пакет Service. убрал.

2024-07-25 17:54 UTC, vkupriya commented on internal/gophermart/server/handlers/handlers.go
> +	ErrorNoContextUser        string = "failed to get user from context value"
согласен - поменял на не экспортируемые. используются только в хэндлерах.

2024-07-25 17:56 UTC, vkupriya commented on internal/gophermart/service/service.go
> +func (g *GophermartService) SvcOrderGetAccrual(order *models.Order) (models.Order, error) {
у меня обрабатывается 429, но только в случае с одним воркером. Постараюсь поменять код для поддержки нескольких воркеров.

2024-07-26 08:47 UTC, vkupriya commented on internal/gophermart/storage/storage.go
> +	var PgErr *pgconn.PgError
да, думаю, что в этот раз точно усвою, что нет смысла экспортировать то, что не должно экспортироваться.  исправил.

2024-07-26 08:52 UTC, vkupriya commented on internal/gophermart/storage/storage.go
> +	tx, err := pool.Begin(ctx)
tx, err := pool.Begin(ctx)

	if err != nil {
		return nil, fmt.Errorf("failed to start a transaction: %w", err)
	}

	defer func() {
		if err := tx.Rollback(ctx); err != nil {
			if !errors.Is(err, pgx.ErrTxClosed) {
				logger.Sugar().Errorf("failed to rollback the transaction", zap.Error(err))
			}
		}
	}()

2024-07-26 08:53 UTC, vkupriya commented on internal/gophermart/storage/storage.go
> +	tx, err := pool.Begin(ctx)
у меня есть Rollback в defer, как было в примерах вебинара.

2024-07-26 09:09 UTC, vkupriya commented on internal/gophermart/gophermart.go
> +				err = fmt.Errorf("a panic occurred: %v", errRec)
Добавил switch/case для проверки типа.

2024-07-26 13:35 UTC, vkupriya commented on internal/gophermart/storage/storage.go
> +	row = db.QueryRow(ctx, querySQL, userid)
переделал - теперь внутри транзакции.

2024-07-29 08:42 UTC, vkupriya commented on internal/gophermart/service/service.go
> +func NewStore(c *models.Config) (Storage, error) {
поменял инициализацию, передаю базу аргументом в GophermartService.

2024-07-29 08:43 UTC, vkupriya commented on internal/gophermart/gophermart.go
> +	context.AfterFunc(ctx, func() {
игнорирую.

2024-07-29 20:30 UTC, vkupriya commented on internal/gophermart/service/service.go
> +				accrualOrder, err := g.SvcOrderGetAccrual(&order)
добавил воркеры.

2024-07-30 09:49 UTC, vkupriya commented on internal/gophermart/service/service.go
> +		tickerPeriod int64 = 10
перенёс в конфигурацию и сделал time.Duration

2024-07-30 09:49 UTC, vkupriya commented on internal/gophermart/service/service.go
> +		httpTimeout       int   = 30
добавил в конфигурацию как time.Duration

2024-07-30 09:50 UTC, vkupriya commented on internal/gophermart/service/service.go
> +	for retry <= retries {
я поменял логику, используя предложение в чате (Пачке).

2024-07-30 13:31 UTC, vkupriya commented on internal/gophermart/gophermart.go
> +			errRec := recover()
добавил миддлеварь.

2024-07-30 13:45 UTC, vkupriya commented on internal/gophermart/service/service.go
> +					order.Status = "NEW"
поменял логику. поднимаю и NEW и PROCESSING. Сброса в NEW не делаю.

2024-07-30 13:49 UTC, vkupriya commented on internal/gophermart/server/handlers/handlers.go
> +	logger := gr.config.Logger
проверку наличия пользователя в контексте? там всего три строки кода.

2024-07-30 13:55 UTC, vkupriya commented on internal/gophermart/gophermart.go
> +	if err := g.Wait(); err != nil {
добавил Go рутину, которая закрывает соединение с базой.

2024-08-01 11:43 UTC, vkupriya commented on internal/gophermart/storage/storage.go
> +	createSchema := []string{
прослушал твой вебинар (очень поучительный) и переделал в миграции.

2024-08-01 11:43 UTC, vkupriya commented on internal/gophermart/service/service.go
> +func (g *GophermartService) SvcOrderGetAccrual(order *models.Order) (models.Order, error) {
переделал.

2024-08-01 11:48 UTC, vkupriya commented on internal/gophermart/service/service.go
> +	logger.Sugar().Debugf("user %s has been registered", user.UserID)
поменял, да так лучше получается - выводить KV пары.

2024-08-01 22:36 UTC, s-shpak approved these changes

2024-08-02 12:50 UTC, merged